### ISSUE TITLE
cdk 2.10 seems to be empty

### ISSUE THREAD

**Issue by meier-rene** [cdk/cdk#1143]
Hi, I dont know how to describe this properly. When I switch from 2.9 to 2.10 there seem to be no content in the cdk maven artifact. I just switched the version number from 2.9 to 2.10. Im importing 
<dependency>
            <groupId>org.openscience.cdk</groupId>
            <artifactId>cdk-bundle</artifactId>
            <version>2.10</version>
</dependency>
I get no warnings from maven during the download of the package artifacts.

During compilation I get failures already at the import statements. All packages are gone.
I checked my local maven repo and while I have a lot of files with version number 2.9 in my repo for 2.10 I only find: 
./org/openscience/cdk/cdk/2.10/cdk-2.10.pom
./org/openscience/cdk/cdk/2.10/cdk-2.10.pom.sha1
./org/openscience/cdk/cdk/2.10/cdk-2.10.jar.lastUpdated
./org/openscience/cdk/cdk/2.10/cdk-2.10.pom.lastUpdated
./org/openscience/cdk/cdk-bundle/2.10/cdk-bundle-2.10.pom.sha1
./org/openscience/cdk/cdk-bundle/2.10/cdk-bundle-2.10.jar.sha1
./org/openscience/cdk/cdk-bundle/2.10/cdk-bundle-2.10.jar
./org/openscience/cdk/cdk-bundle/2.10/cdk-bundle-2.10.jar.lastUpdated
./org/openscience/cdk/cdk-bundle/2.10/cdk-bundle-2.10.pom
./org/openscience/cdk/cdk-bundle/2.10/cdk-bundle-2.10.pom.lastUpdated

Can you please check if your release artifacts got properly created.

**Comment by meier-rene** [comment]
Yes, is like I expected. [Maven Central](https://central.sonatype.com/artifact/org.openscience.cdk/cdk-bundle/2.10/dependencies) shows empty dependencies list for 2.10

**Comment by johnmay** [comment]
The bundle is a empty module which just include all the other modules. Did you actually try running you project?

We do attach the assembled/bundled JAR and all dependencies to the Release notes.

**Comment by johnmay** [comment]
BTW - We really don't recommend using cdk-bundle if you use Maven - you are much better to include what you need.

**Comment by johnmay** [comment]
Hmm it does look like something changed though as you are correct 2.9 pull everything in - there isn't an obvious difference but I will have a poke, thanks.

**Comment by meier-rene** [comment]
> The bundle is a empty module which just include all the other modules. Did you actually try running you project?

I can not run my project, because it does not compile. I changed nothing besides switching he maven dependency from 2.9 to 2.10.

**Comment by meier-rene** [comment]
Ok, instead of including cdk-bundle, I can include for example cdk-core and this makes for example org.openscience.cdk.interfaces.IAtomContainer available. How can I figure out what package is packaged in what artifact?

**Comment by meier-rene** [comment]
I was able to run my project after I removed cdk-bundle and replaced it with
cdk-core
cdk-inchi
cdk-smiles
cdk-silent
cdk-formula
I found the artifacts by finding the class file in the CDK repo and then went up in the filetree until I found a pom file with an artifact. Then I included that artifact. Does this sound reasonable?

**Comment by johnmay** [comment]
I've fixed it - was hard track down but the bundled/shaded JAR was doing something different in a new version of the plugin.

https://github.com/cdk/cdk/commit/ef2463189ee67b0b8e1ba0ced04ea01bf241b11c

You can use cdk-bundle:2.11-SNAPSHOT (when it is deployed) or as you have done the direct dependencies.

**Comment by egonw** [comment]
> when it is deployed

deploy done.

**Comment by Mailaender** [comment]
https://mvnrepository.com/artifact/org.openscience.cdk/cdk-bundle/2.10 still has no dependencies.

**Comment by johnmay** [comment]
Yes, we can't change the release once it's done, there will need to be a new one (2.10.1) - why do you need it, maven projects should not really be including cdk-bundle?

**Comment by Mailaender** [comment]
I tried bundling as described in https://www.vogella.com/tutorials/EclipseJarToPlugin/article.html#adding-a-dependency-to-your-target-file as one large feature, but it didn't resolve the ClassNotFound exceptions in the OSGi environment, so there is no need from my side.
